hmm

diff --git a/clusters/main/kubernetes/tests/kometa/app/helm-release.yaml b/clusters/main/kubernetes/tests/kometa/app/helm-release.yaml
--- a/clusters/main/kubernetes/tests/kometa/app/helm-release.yaml
+++ b/clusters/main/kubernetes/tests/kometa/app/helm-release.yaml
@@ -64,11 +64,11 @@ spec:
               args:
                 - |
                   echo "Creating config.yml file..."
-                  if [ -f /config/config.yml ]; then
+                  if [ -f /app/config/config.yml ]; then
                     echo "Config file exists! Skipping..."
                   else
                     echo "Config file is missing, getting a new one!"
-                    curl -fLvo /config/config.yml https://raw.githubusercontent.com/kometa-team/kometa/master/config/config.yml.template || (echo "Downloading config file, FAILED..." && exit 1)
+                    curl -fLvo /app/config/config.yml https://raw.githubusercontent.com/kometa-team/kometa/master/config/config.yml.template || (echo "Downloading config file, FAILED..." && exit 1)
                   fi
           containers:
             main:
@@ -86,5 +86,5 @@ spec:
     persistence:
       config:
         enabled: true
-        mountPath: /config
+        mountPath: /app/config
         targetSelectAll: true
